# General
edition = "2018"
version = "Two"
unstable_features = true

# Line breaking
newline_style = "Unix"

# Comments
format_code_in_doc_comments = true

# Formatting
imports_layout = "HorizontalVertical"
format_strings = true
merge_derives = true
format_macro_matchers = true
overflow_delimited_expr = true

# Reordering
merge_imports = true

# Shorthands
use_try_shorthand = true
use_field_init_shorthand = true
condense_wildcard_suffixes = true
