name: Documentation

on:
  push:
    branches:
      - master

defaults:
  run:
    shell: bash

jobs:
  docs:
    name: Documentation
    runs-on: ubuntu-latest
    steps:
      - name: Install Rust
        run: |
          rustup set profile minimal
          rustup default nightly

      - name: Checkout source code
        uses: actions/checkout@master
        with:
          persist-credentials: false

      - name: Build
        run: |
          cargo doc --verbose --no-deps --all-features
          CRATE_TEST=$(echo '${{ github.repository }}' | tr '[:upper:]' '[:lower:]' | cut -f2 -d"/")
          echo "<meta http-equiv=\"refresh\" content=\"0; url=${CRATE_TEST/-/_}\">" > target/doc/index.html
          touch target/doc/.nojekyll

      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: Documentation
          path: target/doc

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          ACCESS_TOKEN: ${{ secrets.GH_PAT }}
          BRANCH: gh-pages
          FOLDER: target/doc
