name: Coverage

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  grcov:
    name: Coverage
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          # We don't have branches on OS currently
          # - macOS-latest
          # - windows-latest
        toolchain:
          - nightly
        cargo_flags:
          - "--all-features"
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.toolchain }}
          override: true

      - name: Install grcov
        shell: bash
        run: |
          case "${{ matrix.os }}" in
            ubuntu-latest)
              GRCOV_NAME=grcov-linux-x86_64.tar.bz2
              ;;
            windows-latest)
              GRCOV_NAME=grcov-win-x86_64.tar.bz2
              ;;
            macOS-latest)
              GRCOV_NAME=grcov-osx-x86_64.tar.bz2
              ;;
          esac
          curl -L https://github.com/mozilla/grcov/releases/latest/download/${GRCOV_NAME} | tar jxf -

      - name: Test
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --all --no-fail-fast ${{ matrix.cargo_flags }}
        env:
          CARGO_INCREMENTAL: "0"
          RUSTFLAGS: "-Zprofile -Ccodegen-units=1 -Cinline-threshold=0 -Clink-dead-code -Coverflow-checks=off"

      - name: Generate coverage data
        run: |
          ./grcov target/debug/ \
            --source-dir . \
            --commit-sha ${{ github.sha }} \
            --service-job-id ${{ github.job }} \
            --service-name ${{ github.workflow }} \
            --service-number ${{ github.run_number }} \
            --llvm \
            --branch \
            --ignore-not-existing \
            --ignore "/*" \
            --ignore "C:/*" \
            --ignore "../*" \
            --output-type lcov
            --output-file lcov.info

      - name: Upload coverage to codecov.io
        uses: codecov/codecov-action@v1
        with:
          file: lcov.info
          fail_ci_if_error: true
