name: Lint

on:
  push:
    branches:
      - master
  pull_request:

defaults:
  run:
    shell: bash

env:
  CLIPPY_PARAMS: -D clippy::all -D clippy::pedantic -D clippy::nursery -D clippy::cargo

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Install Rust
        run: |
          rustup set profile default
          rustup default nightly

      - name: Checkout source code
        uses: actions/checkout@master

      - name: Run rustfmt
        run: cargo fmt -- --verbose --check

      - name: Run clippy
        run: cargo clippy --verbose --all-features -- ${{ env.CLIPPY_PARAMS }}
